-------------------------
-- Simplified Chinese Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- 20140731
-------------------------
localization_Chinese_table = {
    calories_table={
        {str="≈1个茶叶蛋",	calories=96},
        {str="≈1片面包",	calories=100},
        {str="≈1瓶冰红茶",	calories=112},
        {str="≈1个煎蛋",	calories=118},
        {str="≈2串羊肉串",	calories=124},
        {str="≈1罐可乐",	calories=153},
        {str="≈3串羊肉串",	calories=186},
        {str="≈2个茶叶蛋",	calories=192},
        {str="≈2片面包",	calories=200},
        {str="≈1碗米饭",	calories=210},
        {str="≈1个馒头",	calories=221},
        {str="≈1根冰糖葫芦",	calories=223},
        {str="≈2瓶冰红茶",	calories=224},
        {str="≈1包小薯条",	calories=224},
        {str="≈1个蛋黄派",	calories=224},
        {str="≈2个煎蛋",	calories=236},
        {str="≈4串羊肉串",	calories=248},
        {str="≈1个汉堡",	calories=260},
        {str="≈1根油条",	calories=270},
        {str="≈1个肉包子",	calories=272},
        {str="≈3个茶叶蛋",	calories=288},
        {str="≈1个甜筒",	calories=290},
        {str="≈3片面包",	calories=300},
        {str="≈2罐可乐",	calories=306},
        {str="≈1包中薯条",	calories=328},
        {str="≈3个煎蛋",	calories=354},
        {str="≈1个蛋挞",	calories=393},
        {str="≈4片面包",	calories=400},
        {str="≈1包大薯条",	calories=402},
        {str="≈2碗米饭",	calories=420},
        {str="≈2个馒头",	calories=442},
        {str="≈2根冰糖葫芦",	calories=446},
        {str="≈1个蛋黄派",	calories=448},
        {str="≈1包方便面",	calories=470},
        {str="≈5片面包",	calories=500},
        {str="≈1盘蛋炒饭",	calories=516},
        {str="≈2个汉堡",	calories=520},
        {str="≈2根油条",	calories=540},
        {str="≈2个肉包子",	calories=544},
        {str="≈2个甜筒",	calories=580},
        {str="≈1碗方便面",	calories=581},
        {str="≈1碗牛肉拉面",	calories=593},
        {str="≈10串羊肉串",	calories=620},
        {str="≈3碗米饭",	calories=630},
        {str="≈3个馒头",	calories=663},
        {str="≈2个蛋挞",	calories=786},
        {str="≈3根油条",	calories=810},
        {str="≈3个肉包子",	calories=816},
    },

    ok='确定',

    hour='小时',
    minute='分钟',
    month='月',
    day='日',
    step="步",
    km='公里',
    minute_format='%d分钟',
    hour_minute_format='%d小时%d分钟',
    hour_format='%d小时',

    welcome_use='欢迎使用小米手环',
    last_week_walked_format='上周共行走%d步',
    last_week_walked_info_format='共走了%d公里、消耗%d千卡',
    last_month_walked_format='上月共行走%d步',
    last_month_walked_info_format='共走了%d公里、消耗%d千卡',

    get_over_format=", 轻松甩掉%d克肥肉",
    click_to_get_help="点击查看如何玩转小米手环",
    take_a_walk="戴上小米手环走一走吧",
    take_a_walk_info="她会随时记录你的运动信息, 做你的健康助手",
    unlock_hint="使用手环智能解锁手机屏幕",
    unlock_hint_info="告别传统密码解锁时代",
    no_data_hint_0="运动的要义不在趣味而在继续持久, 养成习惯",
    no_data_hint_1="慢跑可以帮助你快乐减压, 让你保持一份好心情",
    no_data_hint_2="有氧训练是减肥、强身的一个重要手段, 它包括健身操、跑步、蹬自行车等",
    no_data_hint_3="一个成年人的深度睡眠只占其整个睡眠时间的15%~20%, 也就平均90分钟",
    not_binded_hint="你还没有绑定手环, 点击绑定",
    new_record_info="恭喜, 你创造自己的最高行走纪录",
    new_record_format="新纪录, %d步, %d月%d日",
    today_goal_reached="恭喜, 今天已达成目标",
    week_continue_reach_goal="连续一周达成目标, 赞！",
    challenge_format="你已连续%d天达成目标",
    personal_best_format="个人历史最高记录%d天",
    active_time_format_0="%d分钟",
    active_time_format_1="%d小时",
    active_time_format_2="%d小时%d分钟",
    activie_run_format_0="跑了%s, 赞！",
    activie_run_format_1="狂奔了%s, 好样的！",
    activie_run_format_2="跑了%s, 好耐力！",
    activie_run_consumed="消耗了%d千卡%s",

    get_distance_format="%d米",
    activity_walk_format="%s走了%d步, 共%s",
    activity_walk_consumed_format="消耗了%d千卡%s",

    activity_activity_format="%s活动了%s, 共%s",
    last_night_sleeped_good_format="昨晚睡了%d小时%d分钟, 睡得不错哦",
    last_night_sleeped_normal_format="昨晚睡了%d小时%d分钟",
    deep_sleep_format="深睡%d小时%d分钟",

    battery_low_info="手环电池电量低, 请及时充电",
    battery_very_low_info="手环电量过低即将关闭, 请充电",

    cannot_find_bracelet="无法查找到手环？",
    cannot_find_bracelet_info="请确保手环有电且在手机旁边",
}