-------------------------
-- Traditional Chinese Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- 20140815
-------------------------
localization_zh_rTW_table = {
    calories_table={
        {str="≈1個茶葉蛋",	calories=96},
        {str="≈1片麵包",	calories=100},
        {str="≈1瓶冰紅茶",	calories=112},
        {str="≈1個煎蛋",	calories=118},
        {str="≈2串羊肉串",	calories=124},
        {str="≈1罐可樂",	calories=153},
        {str="≈3串羊肉串",	calories=186},
        {str="≈2個茶葉蛋",	calories=192},
        {str="≈2片麵包",	calories=200},
        {str="≈1碗米飯",	calories=210},
        {str="≈1個饅頭",	calories=221},
        {str="≈1根冰糖葫蘆",	calories=223},
        {str="≈2瓶冰紅茶",	calories=224},
        {str="≈1包小薯條",	calories=224},
        {str="≈1個蛋黄派",	calories=224},
        {str="≈2個煎蛋",	calories=236},
        {str="≈4串羊肉串",	calories=248},
        {str="≈1個漢堡",	calories=260},
        {str="≈1根油條",	calories=270},
        {str="≈1個肉包子",	calories=272},
        {str="≈3個茶葉蛋",	calories=288},
        {str="≈1個甜筒",	calories=290},
        {str="≈3片麵包",	calories=300},
        {str="≈2罐可樂",	calories=306},
        {str="≈1包中薯條",	calories=328},
        {str="≈3個煎蛋",	calories=354},
        {str="≈1個蛋塔",	calories=393},
        {str="≈4片麵包",	calories=400},
        {str="≈1包大薯條",	calories=402},
        {str="≈2碗米飯",	calories=420},
        {str="≈2個饅頭",	calories=442},
        {str="≈2根冰糖葫蘆",	calories=446},
        {str="≈1個蛋黄派",	calories=448},
        {str="≈1包速食麵",	calories=470},
        {str="≈5片麵包",	calories=500},
        {str="≈1盤蛋炒飯",	calories=516},
        {str="≈2個漢堡",	calories=520},
        {str="≈2根油條",	calories=540},
        {str="≈2個肉包子",	calories=544},
        {str="≈2個甜筒",	calories=580},
        {str="≈1碗速食麵",	calories=581},
        {str="≈1碗牛肉拉麵",	calories=593},
        {str="≈10串羊肉串",	calories=620},
        {str="≈3碗米飯",	calories=630},
        {str="≈3個饅頭",	calories=663},
        {str="≈2個蛋塔",	calories=786},
        {str="≈3根油條",	calories=810},
        {str="≈3個肉包子",	calories=816},
    },

    ok='確定',

    hour='小時',
    minute='分鐘',
    month='月',
    day='日',
    step="步",
    km='公里',
    minute_format='%d分鐘',
    hour_minute_format='%d小時%d分鐘',
    hour_format='%d小時',

    welcome_use='歡迎使用小米手環',
    last_week_walked_format='上周共行走%d步',
    last_week_walked_info_format='共走了%d公里、消耗%d千卡',
    last_month_walked_format='上月共行走%d步',
    last_month_walked_info_format='共走了%d公里、消耗%d千卡',

    get_over_format=", 輕鬆甩掉%d克肥肉",
    click_to_get_help="點擊查看如何玩轉小米手環",
    take_a_walk="戴上小米手環走一走吧",
    take_a_walk_info="她會隨時記錄你的運動資訊, 做你的健康助手",
    unlock_hint="使用手環智慧解鎖手機螢幕",
    unlock_hint_info="告別傳統密碼解鎖時代",
    no_data_hint_0="運動的要義不在趣味而在繼續持久, 養成習慣",
    no_data_hint_1="慢跑可以幫助你快樂減壓, 讓你保持一份好心情。",
    no_data_hint_2="有氧訓練是減肥、強身的一個重要手段, 它包括健身操、跑步、踩自行車等。",
    no_data_hint_3="一個成年人的深度睡眠只占其整個睡眠時間的15%~20%, 也就平均90分鐘。",
    not_binded_hint="你還沒有綁定手環, 點擊綁定",
    new_record_info="恭喜, 你創造自己的最高行走紀錄",
    new_record_format="新紀錄, %d步, %d月%d日",
    today_goal_reached="恭喜, 今天已達成目標",
    week_continue_reach_goal="連續一周達成目標, 贊！",
    challenge_format="你已連續%d天達成目標。",
    personal_best_format="個人歷史最高記錄%d天",
    active_time_format_0="%d分鐘",
    active_time_format_1="%d小時",
    active_time_format_2="%d小時%d分鐘",
    activie_run_format_0="跑了%s, 讚！",
    activie_run_format_1="狂奔了%s, 好樣的！",
    activie_run_format_2="跑了%s, 好耐力！",
    activie_run_consumed="消耗了%d千卡%s",

    get_distance_format="%d米",
    activity_walk_format="%s走了%d步, 共%s",
    activity_walk_consumed_format="消耗了%d千卡%s",

    activity_activity_format="%s活動了%s, 共%s",
    last_night_sleeped_good_format="昨晚睡了%d小時%d分鐘, 睡得不錯哦",
    last_night_sleeped_normal_format="昨晚睡了%d小時%d分鐘",
    deep_sleep_format="深睡%d小時%d分鐘",

    battery_low_info="手環電池電量低, 請及時充電",
    battery_very_low_info="手環電量過低即將關閉, 請充電",

    cannot_find_bracelet="無法尋找到手環？",
    cannot_find_bracelet_info="請確保手環有電且在手機旁邊",
}